inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  TargetRubyVersion: 3.0
  Include:
    - bin/*
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - table_sync.gemspec

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

RSpec/ExampleLength:
  Enabled: false

Lint/UnusedBlockArgument:
  AllowUnusedKeywordArguments: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Style/AccessorGrouping:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/HashConversion:
  Exclude:
    - spec/**/*

Style/OpenStructUse:
  Exclude:
    - spec/**/*

RSpec/PendingWithoutReason:
  Enabled: false # Many false positives

RSpec/SkipBlockInsideExample:
  Enabled: false # Many false positives

RSpec/IndexedLet:
  Enabled: false
